<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Consulting</name>
   <tag></tag>
   <elementGuidId>9bed8f08-20b6-4989-a503-27e4a0ba0aca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='topic-description']/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.primary-headline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>66f342c6-40d1-42d3-ae9b-82a5540e17ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-headline</value>
      <webElementGuid>0b050632-1a85-4be3-85f4-5e3690479fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consulting</value>
      <webElementGuid>b1cad2cd-1b09-4010-803a-237ad0868c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topic-description&quot;)/div[@class=&quot;topic-description-content&quot;]/h1[@class=&quot;primary-headline&quot;]</value>
      <webElementGuid>5c3aecc8-cb06-489c-8df2-c2593b4cbd88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='topic-description']/div/h1</value>
      <webElementGuid>8c70ce0d-2ce0-416c-9598-ed29ff19b142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>f68e6a3d-a60f-45c2-bf88-6f925a61fbb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Consulting' or . = 'Consulting')]</value>
      <webElementGuid>6d9862a0-ee32-4d1e-b8f5-8e8581f3e574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
