<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Choose a course</name>
   <tag></tag>
   <elementGuidId>2c36ab36-8bed-496d-b059-f68cf630ccc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.choose-a-course.cus-btn.cus-btn-primary.trackable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0a5d9b6-4d8e-48a9-954c-10bcb663dcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choose-a-course cus-btn cus-btn-primary trackable</value>
      <webElementGuid>b8eeff9b-fcf2-4b71-8010-1cafd890dc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5c46c0f4-7ee3-4d9b-a13c-79486f09bf24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-registration</value>
      <webElementGuid>cfda8d85-4f77-4544-9624-bcb2055b3ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-name</name>
      <type>Main</type>
      <value>choose a course Button Clicked</value>
      <webElementGuid>a5c8fda1-34a8-4b61-95d4-8225be3c19c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-category</name>
      <type>Main</type>
      <value>User engagement</value>
      <webElementGuid>7dc860fa-ba02-4c88-bc52-cf968df8d02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose a course</value>
      <webElementGuid>19dbca8e-5780-45ef-8d44-43d909d0836e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container-fluid kata-container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;hero&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content&quot;]/button[@class=&quot;choose-a-course cus-btn cus-btn-primary trackable&quot;]</value>
      <webElementGuid>09de78d7-b34c-4e2c-9334-2f030bedcc8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/div/div/div/button</value>
      <webElementGuid>8342f25e-4853-4113-a10a-076b6062c6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/button</value>
      <webElementGuid>12a303ea-674b-4f65-84b9-2015bd63880b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Choose a course' or . = 'Choose a course')]</value>
      <webElementGuid>b407b4d7-6fcc-40f1-a98a-3fad02a9684b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
