<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>776ff851-d7a2-4759-a180-f4f7e3e46130</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-header > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='search-header']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1b316519-1957-4ff1-bee2-bf8eeed0ad71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>18px</value>
      <webElementGuid>caadf755-6369-4b70-a9a2-c8e83cbc1b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>18px</value>
      <webElementGuid>ec81f869-0f6c-475f-b352-f3217c1ffee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/academy/header/search.svg</value>
      <webElementGuid>0c3041ac-4555-4c08-9532-318aed187e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/header[@id=&quot;masthead&quot;]/div[@class=&quot;container-fluid kata-container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;primary-menu&quot;]/div[@class=&quot;row align-items-center justify-content-between&quot;]/div[@class=&quot;col col-auto skillate-header-search&quot;]/form[@class=&quot;search_form_shortcode&quot;]/div[@class=&quot;search-wrap&quot;]/div[@id=&quot;search-toggle&quot;]/button[@id=&quot;search-header&quot;]/img[1]</value>
      <webElementGuid>e2a7067a-f419-43c3-af52-0d888e811b14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='search-header']/img</value>
      <webElementGuid>628b152f-00c0-4c66-99e4-7b885e18eed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/academy/header/search.svg')]</value>
      <webElementGuid>4e7f2740-8d5f-4560-a6b5-cf76329bcd3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>acd9fa87-ded9-481a-b185-632c6c49acd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/academy/header/search.svg']</value>
      <webElementGuid>75bd0b27-1f06-44fa-a5e3-b766510b5939</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
