<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_s</name>
   <tag></tag>
   <elementGuidId>e77af3d2-cfe4-4e7d-8353-8e7f86a22f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchwordd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchwordd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3dd2ff1-d47c-41b2-b49b-16c8be4f32cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute</value>
      <webElementGuid>74f33986-8210-40f1-a49a-364c722f60d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6fd1e18-fe53-4091-8690-20a7a0c9831c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d72247a0-cdde-464e-a156-0bc43132e97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>3eb25632-1655-473f-8782-74ab383d6caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchwordd</value>
      <webElementGuid>83bd8515-b8fc-47cb-a41c-9315f35da4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page&quot;)/header[@id=&quot;masthead&quot;]/div[@class=&quot;container-fluid kata-container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;primary-menu&quot;]/div[@class=&quot;row align-items-center justify-content-between&quot;]/div[@class=&quot;col col-auto skillate-header-search&quot;]/form[@class=&quot;search_form_shortcode&quot;]/div[@class=&quot;search-wrap&quot;]/div[@id=&quot;search-toggle&quot;]/input[@id=&quot;searchwordd&quot;]</value>
      <webElementGuid>09705869-8d81-4090-87f7-c13fb7b95ea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchwordd']</value>
      <webElementGuid>9686b47d-94b7-48f2-9df8-5cd87f003c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-toggle']/input</value>
      <webElementGuid>7b2b37b4-43fb-4e22-9327-9bc2ee0be179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0b1c267e-11d4-4cde-a1e9-6ab0bd572361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @name = 's' and @id = 'searchwordd']</value>
      <webElementGuid>b4c3a781-1d85-4c02-ad3b-057adebd67a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
