<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>6b8ccf6f-6e85-400c-8eb4-cbbd74bea1b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-registration > div.modal-dialog > div.skillate-signin-popup-inner.modal-content > button.btn-close > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-registration']/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>661adb16-198b-40b7-84f8-adbf667778b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da6e9ec4-04b0-4713-bd89-3f5cec408db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>6fdf6cee-4cb7-4c4e-be47-29c5683c99bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-registration&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;skillate-signin-popup-inner modal-content&quot;]/button[@class=&quot;btn-close&quot;]/span[1]</value>
      <webElementGuid>077d173c-a15f-4abe-bc5f-c1657ce22d92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-registration']/div/div/button/span</value>
      <webElementGuid>6bb5149f-fdc5-47ae-92cb-4bb84f01e7f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>33eac6f6-6451-416d-a2b6-075b24f84db5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>de1dea3f-68d0-4d46-9726-89c6707686bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
