<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Aguascalientes_1</name>
   <tag></tag>
   <elementGuidId>3908c7bc-a7b8-48bc-ba50-a4784cbd6c32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='li63716780']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#li63716780</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1f224010-9931-4ae1-9b61-fc592f3b0f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option WizardFieldInput select2-results__option--highlighted</value>
      <webElementGuid>69f8067f-b138-4dc3-bd2c-e1c04eed59a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>275fcff3-7c1c-4f8f-8b8f-227bae04dbe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c9bea95-19d4-4028-aa65-d6847cae410e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>li63716780</value>
      <webElementGuid>b8631d51-ea6b-4969-8737-be7990707af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>li63716780</value>
      <webElementGuid>2b2abb47-0e90-4d39-aeed-5929394dbcc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aguascalientes</value>
      <webElementGuid>3e97315d-429a-4e79-99aa-8446198059f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li63716780&quot;)</value>
      <webElementGuid>c86cb504-ebcb-44ca-b084-ad95af98e940</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='li63716780']</value>
      <webElementGuid>a8dd0dac-f55e-48ab-9e1b-1d90ad30d27b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-9337-results']/li</value>
      <webElementGuid>5468b8b8-7081-4a00-879f-9dee29dc87ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>5d487858-42b4-4773-8209-6e73022a4c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'li63716780' and (text() = 'Aguascalientes' or . = 'Aguascalientes')]</value>
      <webElementGuid>63bde2ef-1353-4ad0-8d9d-b1b0d186bf64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
