<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Advertising, Marketing  Commerce</name>
   <tag></tag>
   <elementGuidId>dd51d9e8-83ff-4629-96fa-37542e20b154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='li1233']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#li1233</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c1637dab-da41-47cb-b06a-d0418de38771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option WizardFieldInput select2-results__option--highlighted</value>
      <webElementGuid>619618a1-b8da-48fe-8763-42f124fe911a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a7f168de-c7a7-4b04-be52-dac77538e321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b975c668-74f8-4f31-b175-c9c01307f587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>li1233</value>
      <webElementGuid>7176fb2a-76bb-449a-a0a0-3181de982efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>li1233</value>
      <webElementGuid>07ba7dca-fd96-495c-bd8e-37057d380906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Advertising, Marketing &amp; Commerce</value>
      <webElementGuid>92a3ac2a-befa-4ba7-b9af-dfc9dfc0efd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li1233&quot;)</value>
      <webElementGuid>07f439e5-2fab-4c29-a440-a2a2e0c844ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='li1233']</value>
      <webElementGuid>ffb37e4b-a24d-4e63-a7b7-6407faee7fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-9338-results']/li[3]</value>
      <webElementGuid>70f3ea86-79a0-4485-a09e-88e90d9cbe10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[3]</value>
      <webElementGuid>2db825c1-0777-4607-b73f-d022a17ba4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'li1233' and (text() = 'Advertising, Marketing &amp; Commerce' or . = 'Advertising, Marketing &amp; Commerce')]</value>
      <webElementGuid>cd10a9ef-0161-4d5c-b85d-4ad253e3d543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
