<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Aguascalientes</name>
   <tag></tag>
   <elementGuidId>182d45b8-ff82-4230-b44c-9452460dae92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='li63716425']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#li63716425</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8e404b6b-ab37-4ac8-b149-4a0d04fb238e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option WizardFieldInput select2-results__option--highlighted</value>
      <webElementGuid>5050689e-9b06-451e-a1b0-be63c5ac45c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>affc1b47-f99c-4815-a591-f471bb43c5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cac98293-6b87-45e4-8e8a-1d029a5690c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>li63716425</value>
      <webElementGuid>3b0cddb8-e6db-4804-89c0-b493df6f7556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>li63716425</value>
      <webElementGuid>f900a4ec-05bb-4468-a1bd-820084578206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aguascalientes</value>
      <webElementGuid>29f3ff39-0caf-447c-bf51-c5e1db507bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li63716425&quot;)</value>
      <webElementGuid>62df90c1-7d4f-4268-bb32-0d06101631e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='li63716425']</value>
      <webElementGuid>e97841a2-c28d-4e0c-ae57-f38a6da043b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-9336-results']/li</value>
      <webElementGuid>6b73ef8f-6bcf-460d-bd1b-5afe06b9d1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>49518ed7-92d1-4507-bfbb-3798fcbb573c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'li63716425' and (text() = 'Aguascalientes' or . = 'Aguascalientes')]</value>
      <webElementGuid>1e4cf152-1ed4-4a2d-a9d0-0e9a8f7b6822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
