<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Experienced</name>
   <tag></tag>
   <elementGuidId>5daa998d-2249-4810-a26f-67ee3930f618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='li479']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#li479</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>799f51ef-db34-439c-a48f-f7ad6a645dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option WizardFieldInput select2-results__option--highlighted</value>
      <webElementGuid>7160f3fc-6b89-489f-88fa-60f4ee39a300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>795dc608-5681-4f36-a467-d290daba2969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0526c034-35d3-4b49-949b-89fdc0a56c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>li479</value>
      <webElementGuid>a5c32dd3-e6c6-47e5-a03e-5465aa522cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>li479</value>
      <webElementGuid>bb6643d1-f3ec-4a23-9ab2-9c269a2f342a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Experienced</value>
      <webElementGuid>1adc0e0a-260e-4f4f-a62d-52be90946bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li479&quot;)</value>
      <webElementGuid>061a0f93-c8ba-4603-b19a-0505889d1d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='li479']</value>
      <webElementGuid>24719252-a97c-47ba-a28a-c53cac6179bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-9339-results']/li[3]</value>
      <webElementGuid>a4c75bc6-9a76-4e91-9cc6-d53c27c19640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li[3]</value>
      <webElementGuid>a0634d67-37e8-43d6-a8f9-a12a9a4368ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'li479' and (text() = 'Experienced' or . = 'Experienced')]</value>
      <webElementGuid>432489db-d61b-4f4e-9ebc-34e894a1e72b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
