<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Jersey City</name>
   <tag></tag>
   <elementGuidId>8072d867-2074-460a-8171-d06f282bec55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='li2780']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#li2780</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>87b53d21-b1fd-4f07-a9b8-154d77246d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option WizardFieldInput select2-results__option--highlighted</value>
      <webElementGuid>ae026846-d6b8-4781-99bf-edd62df2c127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>ae1f2486-a8d0-4922-a858-6677037f4f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb6c6fb8-3f35-413f-ba53-cacbab3bcaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>li2780</value>
      <webElementGuid>bd9cf7cf-728d-4acb-be01-28799b10fb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>li2780</value>
      <webElementGuid>e694257e-de12-4559-b9ab-a815be067f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jersey City</value>
      <webElementGuid>35ffd6a3-cf11-4de4-a2bb-c6ab7ce9d439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li2780&quot;)</value>
      <webElementGuid>c88a585c-efce-48fa-acf4-fce594642ccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='li2780']</value>
      <webElementGuid>82d81785-8fa9-4bee-9a6f-857f50f7c86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-9337-results']/li</value>
      <webElementGuid>6707c79a-2728-432b-89ee-d562278c0d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span/span/ul/li</value>
      <webElementGuid>9d1a3f01-5c62-47ba-abc3-d02350e67381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'li2780' and (text() = 'Jersey City' or . = 'Jersey City')]</value>
      <webElementGuid>715b7dbe-0f2f-4aef-8400-89049335a5d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
