<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_careers-thumbnail-img</name>
   <tag></tag>
   <elementGuidId>08ba4fa1-f057-4a0a-9709-319769788b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='customExp']/div[5]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.careers-img-wrapper > img.careers-thumbnail-img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e1325aaa-678b-4d15-a342-07b1bd37b52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www2.deloitte.com/content/dam/Deloitte/us/Images/life-at-deloitte/new-careers-thumbnail-w-copy.jpeg</value>
      <webElementGuid>e0ea9594-31a7-4a71-9e3f-4b382e55bf45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>careers-thumbnail-img</value>
      <webElementGuid>2aaccb37-b246-4894-b456-31b3528457d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customExp&quot;)/div[@class=&quot;frag-container careers active&quot;]/div[@class=&quot;frag-content&quot;]/div[@class=&quot;careers-img-wrapper&quot;]/img[@class=&quot;careers-thumbnail-img&quot;]</value>
      <webElementGuid>ff80291d-3513-4295-9e33-9d1b0522ba12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='customExp']/div[5]/div/div/img</value>
      <webElementGuid>64cf1fa7-7a32-41a7-9ba7-7399254aa475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www2.deloitte.com/content/dam/Deloitte/us/Images/life-at-deloitte/new-careers-thumbnail-w-copy.jpeg')]</value>
      <webElementGuid>482c7c21-58e7-47c7-821b-4e75d89ad204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/img</value>
      <webElementGuid>ab2f14ff-c78e-4153-9426-8d5894fdbf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www2.deloitte.com/content/dam/Deloitte/us/Images/life-at-deloitte/new-careers-thumbnail-w-copy.jpeg']</value>
      <webElementGuid>7ed98b7d-ea4a-47de-be1c-6d0bfba69c63</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
