<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Careers</name>
   <tag></tag>
   <elementGuidId>c3dc4a68-228b-4767-b145-c434c560ebf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='customExp']/div[2]/div/div/div[2]/div[2]/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nav-cta-wrapper.careers > p.cta-txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a06e3851-fba4-47be-a358-4cbb67992ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cta-txt</value>
      <webElementGuid>06fd56ad-57c6-45ad-9b01-ec4c5a4ef496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navaction</name>
      <type>Main</type>
      <value>careers</value>
      <webElementGuid>ac29a484-6968-4b21-a8d5-1e76616a9c54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Careers</value>
      <webElementGuid>4778485d-59d4-427f-a3f6-082d614d358e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customExp&quot;)/div[@class=&quot;frag-container home active&quot;]/div[@class=&quot;frag-content&quot;]/div[@class=&quot;home-nav-group&quot;]/div[@class=&quot;nav-group-col&quot;]/div[@class=&quot;nav-cta-wrapper careers&quot;]/p[@class=&quot;cta-txt&quot;]</value>
      <webElementGuid>2acd730c-a677-4bb0-bb4f-1ccfe57ed3d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='customExp']/div[2]/div/div/div[2]/div[2]/p</value>
      <webElementGuid>d6245305-ae3c-4986-9b16-ab48d804d403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/p</value>
      <webElementGuid>98c39f15-7b45-478c-9c51-f18c4c82aa11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Careers' or . = 'Careers')]</value>
      <webElementGuid>7b518e90-bc70-4812-85c1-f33c987fe72a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
