<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Culture</name>
   <tag></tag>
   <elementGuidId>9104d386-8024-4215-adbf-4045bbc3949b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='customExp']/div[2]/div/div/div[3]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nav-cta-wrapper.culture > p.cta-txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f0bd5daf-f685-40bd-b0d5-d738739820a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cta-txt</value>
      <webElementGuid>e572edd5-187e-46ee-9bb6-a3a91dfaeaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navaction</name>
      <type>Main</type>
      <value>culture</value>
      <webElementGuid>d777c80d-60d1-49d2-b749-78db92608506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Culture</value>
      <webElementGuid>93b8aea6-591e-4c78-bc58-8d58e5ff267f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customExp&quot;)/div[@class=&quot;frag-container home active&quot;]/div[@class=&quot;frag-content&quot;]/div[@class=&quot;home-nav-group&quot;]/div[@class=&quot;nav-group-col&quot;]/div[@class=&quot;nav-cta-wrapper culture&quot;]/p[@class=&quot;cta-txt&quot;]</value>
      <webElementGuid>4ee849ff-5069-496c-a6a0-661c993ed731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='customExp']/div[2]/div/div/div[3]/div/p</value>
      <webElementGuid>4f22a245-760a-44a4-8f13-e2090bbb8ff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/p</value>
      <webElementGuid>23f1a553-69ec-4a3d-b55b-bfc5de3e9df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Culture' or . = 'Culture')]</value>
      <webElementGuid>ec5ee6ea-5e28-424e-aee5-c476faf4f30d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
