<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_OurPeople</name>
   <tag></tag>
   <elementGuidId>4038000d-0353-4e13-95e8-1535eda539ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='customExp']/div[2]/div/div/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.nav-cta-wrapper.people > p.cta-txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>43319e4a-9d10-421a-ae98-2bd2777e68d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cta-txt</value>
      <webElementGuid>9402cd81-c436-4b80-b46c-246b2eda1f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navaction</name>
      <type>Main</type>
      <value>people</value>
      <webElementGuid>5053d521-1226-44e0-a8d0-a1acd49a37c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OurPeople</value>
      <webElementGuid>18365a7e-9622-4fba-9a0e-43a94efaa5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customExp&quot;)/div[@class=&quot;frag-container home active&quot;]/div[@class=&quot;frag-content&quot;]/div[@class=&quot;home-nav-group&quot;]/div[@class=&quot;nav-group-col&quot;]/div[@class=&quot;nav-cta-wrapper people&quot;]/p[@class=&quot;cta-txt&quot;]</value>
      <webElementGuid>6ce1e42d-2e03-4303-a81d-c94043a82746</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='customExp']/div[2]/div/div/div[2]/div/p</value>
      <webElementGuid>f8f7f915-3fb4-4aff-bc3f-c503583c226c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>f4ca9139-973f-4fd7-97e4-1cf86ae58e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'OurPeople' or . = 'OurPeople')]</value>
      <webElementGuid>f51ba214-5410-4bf6-bd8a-09aedf0a7db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
