<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_WhyDeloitte</name>
   <tag></tag>
   <elementGuidId>a2948b98-f8be-49e7-a122-44e8de62f44d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='customExp']/div[2]/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.cta-txt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a96fb72d-bbf8-46ba-827b-59258ead9979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cta-txt</value>
      <webElementGuid>1c5cbab8-07b1-4c67-aa38-ab4adba56b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navaction</name>
      <type>Main</type>
      <value>why-deloitte</value>
      <webElementGuid>ada3144d-0605-4d47-bd1a-78291040328b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WhyDeloitte</value>
      <webElementGuid>b200fd50-d486-49f2-b5b3-00a6c9e10b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customExp&quot;)/div[@class=&quot;frag-container home active&quot;]/div[@class=&quot;frag-content&quot;]/div[@class=&quot;home-nav-group&quot;]/div[@class=&quot;nav-group-col&quot;]/div[@class=&quot;nav-cta-wrapper why-deloitte&quot;]/p[@class=&quot;cta-txt&quot;]</value>
      <webElementGuid>6c75188f-9e02-4823-ad2c-3b9e11b3c531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='customExp']/div[2]/div/div/div/div/p</value>
      <webElementGuid>4eec2f90-77a3-4ae8-ab17-b50140b6ad1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/p</value>
      <webElementGuid>d762e77d-1af4-490a-9529-fc65b24ed504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'WhyDeloitte' or . = 'WhyDeloitte')]</value>
      <webElementGuid>de03c2a8-3970-4184-b90e-0a6c86cef86b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
