<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Results for tax</name>
   <tag></tag>
   <elementGuidId>68c72ad7-fd1d-4523-9d04-7ff628e524c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cmp-search-page']/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.cmp-search-page__title.aem-GridColumn.aem-GridColumn--default--1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>81addaf9-55c4-4d7a-9ded-c687e6c9dbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-search-page__title aem-GridColumn aem-GridColumn--default--1</value>
      <webElementGuid>be593025-fed8-48e7-b2ed-63a9b027a8bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Results for “tax”</value>
      <webElementGuid>08fb5a85-f56e-45b6-860a-ad5d04aec0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmp-search-page&quot;)/div[@class=&quot;aem-Grid aem-Grid--1&quot;]/h1[@class=&quot;cmp-search-page__title aem-GridColumn aem-GridColumn--default--1&quot;]</value>
      <webElementGuid>5fa49ebe-2504-4fc4-97a1-20783d31165d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmp-search-page']/div/h1</value>
      <webElementGuid>973d85eb-e0c7-4cae-916c-744926b1d181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>664786d0-c43c-4d28-8202-3e5177a6fa05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = ' Results for “tax”' or . = ' Results for “tax”')]</value>
      <webElementGuid>dd6fe2e1-e2c5-465c-91fc-a40ecea1a758</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
