<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_dropdown_icon</name>
   <tag></tag>
   <elementGuidId>31bbb22a-7173-499d-9eb2-a53222805059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dropdown_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[2]/div/div[3]/div/div[2]/div[5]/div[3]/div/div[2]/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6bc77186-3c3c-4094-9a69-dbe02254e389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_icon</value>
      <webElementGuid>730769bf-ff78-4a99-9960-bac2ca8f3770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;Pricing_wrapPricing__KL0Xj&quot;]/div[@class=&quot;pricing_block_section&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;package_content&quot;]/div[@class=&quot;pricing_package_section pricing_package_platform active&quot;]/div[@class=&quot;package_item premium&quot;]/div[@class=&quot;product_section quality_management&quot;]/div[@class=&quot;wrap_content&quot;]/div[@class=&quot;product_item&quot;]/div[@class=&quot;product_price_input_dropdown&quot;]/div[@class=&quot;dropdown_selected placeholder&quot;]/div[@class=&quot;dropdown_icon&quot;]</value>
      <webElementGuid>a10b7c22-167d-43f5-bfcd-056517037f31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div/div[3]/div/div[2]/div[5]/div[3]/div/div[2]/div/div[3]</value>
      <webElementGuid>c7b35020-96c3-4b8a-93ad-3087a572d943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/div/div[2]/div/div[3]</value>
      <webElementGuid>3dbb48a9-0679-48f9-826f-d75b444e5b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
