<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputinput_platform_testcloud_number</name>
   <tag></tag>
   <elementGuidId>ab5fc092-4126-490b-a06e-0665eea62480</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_platform_testcloud_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_platform_testcloud_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a935115-2da7-4c18-813b-0d95fe31c9a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>859f9a31-6542-49cf-9b65-3e7eee0d31af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0433d7c6-19a5-497f-b311-35259ce2b1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_platform_testcloud_number</value>
      <webElementGuid>85e9bd4f-a25f-4eeb-a576-60ba486e505f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1b1d310c-d13a-4135-a4b5-859044cc3e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-changed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9604ce90-b22f-4db9-8e69-3f1b59e42e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_platform_testcloud_number&quot;)</value>
      <webElementGuid>c31c0e1a-0fd9-47c9-b70a-f60b359f5520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_platform_testcloud_number']</value>
      <webElementGuid>9771c80c-b5a1-4e4f-9934-15997571cc48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div/div[3]/div/div[2]/div[4]/div[3]/div/div[2]/input</value>
      <webElementGuid>7385192e-d129-4aff-8bdc-2cb9cb9b571f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div[2]/input</value>
      <webElementGuid>aa9998fd-d92c-41a2-874b-3c809c6ff58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'input_platform_testcloud_number']</value>
      <webElementGuid>bec10ad7-9d32-429e-8606-31dea95c22a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
