<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputinput_platform_kse_number</name>
   <tag></tag>
   <elementGuidId>4d7709a8-1f2d-4236-bbf1-3dbe35c717c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_platform_kse_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_platform_kse_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d36519ac-213d-439d-8615-358ba3149c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>dfbe5f75-8559-442d-b8fa-e8664f28320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2bf05448-db35-43e5-ab2b-1f45386359ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_platform_kse_number</value>
      <webElementGuid>d871c1e4-ee58-4425-9939-5cf7a6cd76d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>62e06dc8-73fe-420e-9888-5948dc3ea56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-changed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f732e96-8e32-4cc3-836a-10bef78a75bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_platform_kse_number&quot;)</value>
      <webElementGuid>22f64482-31ad-4248-a8f3-364927bf1497</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_platform_kse_number']</value>
      <webElementGuid>558f9714-668a-49d7-ba13-75342bf26848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div/div[3]/div/div[2]/div[3]/div[3]/div/div[2]/input</value>
      <webElementGuid>5fbeff5c-22db-4fda-8350-9ca3d0808779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>47d360cf-3bb7-483b-acd9-514257dbfd1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'input_platform_kse_number']</value>
      <webElementGuid>fb6402e0-fa30-43cc-b85f-18a49e31fcd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
