<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputinput_platform_kre_number</name>
   <tag></tag>
   <elementGuidId>ec509132-ea37-482b-a324-09432bc84474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input_platform_kre_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input_platform_kre_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>011629c7-44f4-4bce-9e8d-e80b714ee6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6ac3760d-3222-4c86-84e9-7a60fd581e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6320bb31-7029-4e2d-b12d-27f790fd6c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_platform_kre_number</value>
      <webElementGuid>813c1269-3a42-4d72-b773-d21c8d3fd3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>854fdc7f-d1dc-46bb-bdbd-6faac72d3e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-changed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5228b682-0173-4c6e-99dd-08c70d9aa1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_platform_kre_number&quot;)</value>
      <webElementGuid>307bcf00-c015-417d-bc5c-c6242b9ed848</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input_platform_kre_number']</value>
      <webElementGuid>f4f48ea5-9650-47d9-81dc-18d2d7bfecd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div/div[3]/div/div[2]/div[4]/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>af873c39-c09a-469a-b0fd-ad2a48c95135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>7dbfef41-89e2-4fa8-a2d7-c224d48ef0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'input_platform_kre_number']</value>
      <webElementGuid>b4574ea3-2eb4-476e-b920-c4e9ba9097b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
