<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divwistia_87.big_play_button_background</name>
   <tag></tag>
   <elementGuidId>5853e7b6-25cb-4699-bf17-4186a20403e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wistia_87.big_play_button_background']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e5dc4420-0bdc-47a4-bdd2-40acdf094d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wistia_87.big_play_button_background</value>
      <webElementGuid>96512d5b-2262-4b1b-aee2-af88c134f0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wistia_87.big_play_button_background&quot;)</value>
      <webElementGuid>4632d328-7f89-43bc-b49a-2dddf718a33a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wistia_87.big_play_button_background']</value>
      <webElementGuid>13c6b325-4fe9-4471-a40e-1f8e7e12305e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wistia_71.thumbnail']/div[2]</value>
      <webElementGuid>7ad3a9df-0985-4fe0-9ddc-ff02255fc885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div[2]</value>
      <webElementGuid>932ecb32-7b8e-454f-a9c3-24f65b943474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wistia_87.big_play_button_background']</value>
      <webElementGuid>02334d94-0552-4942-9bb0-54c35610bf75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
