<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rating</name>
   <tag></tag>
   <elementGuidId>a3f64836-c44c-4bd1-ad2a-68208bbada72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[2]/div[2]/div[2]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rating</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e425dd7b-918f-470e-a6cf-488748236208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rating</value>
      <webElementGuid>ae30a873-f627-44d0-80ec-0d5f6711a036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/view_a_demo/reskin_may_2023/ratings.svg</value>
      <webElementGuid>ae0ae3cc-22ca-44e7-84a0-4c85507a9a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>4.4/5 stars</value>
      <webElementGuid>2def3dc9-4331-4f6b-8658-38d98542eb4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;ViewADemo_wrappingViewADemo__y3r6W&quot;]/div[@class=&quot;view-a-demo&quot;]/div[@class=&quot;cta&quot;]/div[@class=&quot;testimony&quot;]/div[@class=&quot;ratings&quot;]/img[@class=&quot;rating&quot;]</value>
      <webElementGuid>e79dcdfe-727b-4675-b3ee-e4401408207a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div[2]/div[2]/div/img</value>
      <webElementGuid>9f549b2d-c634-4f53-9d21-8532a3b25a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='4.4/5 stars']</value>
      <webElementGuid>228e25df-7b74-4445-86b1-966c2b6366a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/img</value>
      <webElementGuid>f0d99248-0082-441e-8c74-1bdb36441db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/view_a_demo/reskin_may_2023/ratings.svg' and @alt = '4.4/5 stars']</value>
      <webElementGuid>52d4669f-6d65-47ff-8107-2fdcbf164019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
