<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_industry</name>
   <tag></tag>
   <elementGuidId>4540e55f-41f5-4b21-bb81-7fa28527336d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[2]/div[2]/div[2]/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.industry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>333b2f72-0971-4806-8ed1-a4a5a4d75e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>industry</value>
      <webElementGuid>c9e339ff-928e-40d5-ae62-17a00711c00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/view_a_demo/reskin_may_2023/gartner.svg</value>
      <webElementGuid>ed3eb8b7-e06e-4513-994d-db13f3ea9645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gartner logo</value>
      <webElementGuid>17853b7c-66fc-4c60-8671-eab104bb4b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;ViewADemo_wrappingViewADemo__y3r6W&quot;]/div[@class=&quot;view-a-demo&quot;]/div[@class=&quot;cta&quot;]/div[@class=&quot;testimony&quot;]/div[@class=&quot;industries&quot;]/img[@class=&quot;industry&quot;]</value>
      <webElementGuid>762c340e-a7f5-4239-aaa9-eae9fa415c6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[2]/div[2]/div[2]/div[2]/img</value>
      <webElementGuid>73e966e8-b803-4479-ac50-266af89a9e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gartner logo']</value>
      <webElementGuid>ce7a10cd-7fe7-4ed7-8e18-c6af25e4c962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/img</value>
      <webElementGuid>49ac30c4-edab-4e1e-a203-e6bd8c526acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/view_a_demo/reskin_may_2023/gartner.svg' and @alt = 'Gartner logo']</value>
      <webElementGuid>37e436d1-4617-4201-8dfc-21898b06468e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
