<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign up</name>
   <tag></tag>
   <elementGuidId>7e497833-e766-4339-b2f2-af15c54f4445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_sign_up_link']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.button_sign_in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39efea59-73a6-4628-a0de-d9ad3495b4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_sign_in</value>
      <webElementGuid>21db008d-3922-458e-a843-d15fd7fd6dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>c59f2e8b-5380-4df5-ab96-b49895efc635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_sign_up_link&quot;)/div[@class=&quot;button_sign_in&quot;]</value>
      <webElementGuid>dd94f396-f1ae-4286-9d1f-2dba47260449</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn_sign_up_link']/div</value>
      <webElementGuid>aca4cb81-d2ed-4106-8566-97625763de42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>1c46bef7-31aa-4bd2-9b14-d01d8f1d40c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign up' or . = 'Sign up')]</value>
      <webElementGuid>a0889c68-4bd5-482e-aded-c7bdae146cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[2]/a/div</value>
      <webElementGuid>4ca05af1-dde9-44f5-9587-31b5530da872</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
