<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Consulting</name>
   <tag></tag>
   <elementGuidId>fab9e0b4-75bc-4721-9495-5087fa4b7549</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='list1']/div/div/div[2]/ul/li[2]/h4/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2958b68b-e94e-4fce-997e-db8e76f59098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/us/en/services/consulting.html?icid=top_consulting</value>
      <webElementGuid>634b5959-0167-4a42-8248-958afa412784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>567bd368-a616-45c4-9431-fca09062eecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consulting</value>
      <webElementGuid>fa37efcb-838d-4196-8d93-271de5535cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list1&quot;)/div[@class=&quot;cmp-pr-nav__menu open menu-hover&quot;]/div[@class=&quot;cmp-container-width aem-Grid aem-Grid--12&quot;]/div[@class=&quot;cmp-pr-nav__menu__links-wrapper aem-GridColumn aem-GridColumn--default--9 aem-GridColumn--phone--12&quot;]/ul[@class=&quot;cmp-pr-nav__menu__links-section aem-Grid aem-Grid--12&quot;]/li[@class=&quot;cmp-pr-nav__menu__item aem-GridColumn aem-GridColumn--default--4 aem-GridColumn--phone--12 navigation-column&quot;]/h4[1]/a[1]</value>
      <webElementGuid>5b47cbc3-4401-42ce-8ca8-3277fa1dec2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='list1']/div/div/div[2]/ul/li[2]/h4/a</value>
      <webElementGuid>02983259-b0ad-434e-bc51-14ece099b690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Consulting')])[2]</value>
      <webElementGuid>093d686f-d48d-44a3-b6dc-4b749a7d225f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/us/en/services/consulting.html?icid=top_consulting')]</value>
      <webElementGuid>ef175510-2787-4f25-ae54-15ab21223319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/h4/a</value>
      <webElementGuid>86d5e23c-c534-426d-ac81-1b34203899d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/us/en/services/consulting.html?icid=top_consulting' and (text() = 'Consulting' or . = 'Consulting')]</value>
      <webElementGuid>ba19212b-3ea3-42fd-928f-046d05bcbcc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
