<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_cmp-advanced-search__button</name>
   <tag></tag>
   <elementGuidId>ccc2ab0a-93f7-4332-aee4-a899ce82a6aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cmp-advanced-search']/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.cmp-advanced-search__button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d1930d2c-0716-4ddc-8e3f-e1f0b78b0310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-advanced-search__button</value>
      <webElementGuid>bedb4f56-c85b-452e-a772-e94708c6597b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>1c98bea4-2097-48c3-af7b-1e5f0a746058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmp-advanced-search&quot;)/div[@class=&quot;cmp-advanced-search__form ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;cmp-advanced-search__field&quot;]/button[@class=&quot;cmp-advanced-search__button&quot;]</value>
      <webElementGuid>3a6d76b4-c9f1-4983-86da-b1ebd9709b22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmp-advanced-search']/div/div[2]/button</value>
      <webElementGuid>d530f8cd-bf65-4595-9c61-a1d17beb74c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3f119d41-c08a-4bed-9f74-c6ac675f38bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Search']</value>
      <webElementGuid>d7a9e946-b216-4b95-a139-72adb4b47dea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
