<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-search</name>
   <tag></tag>
   <elementGuidId>73557718-09b8-4fac-b144-ab5a7658f632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='list4']/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list4 > a.cmp-pr-nav__item__link > i.icon-chevron</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3e2b2c29-7ca3-47d8-88c6-1591e931e01b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-chevron</value>
      <webElementGuid>0e492984-8697-4f16-80f1-1ace1fb61440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list4&quot;)/a[@class=&quot;cmp-pr-nav__item__link&quot;]/i[@class=&quot;icon-chevron&quot;]</value>
      <webElementGuid>ffd9665c-2ef4-4054-8c08-e392e4c25116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='list4']/a/i</value>
      <webElementGuid>f1906b49-a4b4-4719-85e1-fa8f2207b90c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/i</value>
      <webElementGuid>fea6374d-26dc-4478-9803-a59224b34815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmp-advanced-search']/div/div[2]/button/i</value>
      <webElementGuid>926190e7-503f-4136-944d-df57ea1b4f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/i</value>
      <webElementGuid>95d419f7-4917-4f5c-b473-32937da0916f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='header__ut-nav__search-icon']/button/i</value>
      <webElementGuid>e5845e28-4dd7-457f-aea5-587f5a256f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/button/i</value>
      <webElementGuid>f30ee6b6-cecd-425a-8fa2-2a42b77c4c51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
