<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cmp-advanced-search__input ng-untouch_fd955c</name>
   <tag></tag>
   <elementGuidId>6e7a8886-63c3-4955-8f11-453c61a1fa0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.cmp-advanced-search__input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87e3910e-b60b-4347-8ac3-d21dcc28b64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e12db59f-0dfd-4ac6-a24a-1f188ac71874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7da103d5-710b-4bfc-aa93-44ddfb947fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d911a34c-a9ed-4c7d-aa73-5dbc8f0ef6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>searchTerm</value>
      <webElementGuid>cdeec65c-71c9-4fb0-b5a2-e2f885337247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-advanced-search__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b6b49ac1-f96b-4b36-a665-701c1bc566bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>76065dfb-4f84-403d-86b6-bc02354c8808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmp-advanced-search&quot;)/div[@class=&quot;cmp-advanced-search__form ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;cmp-advanced-search__field&quot;]/input[@class=&quot;cmp-advanced-search__input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>5c9761cd-a9f5-4d39-bac1-d03c79f8e808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='']</value>
      <webElementGuid>11007a70-9c42-4e3d-9ad1-24c0be2b5465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmp-advanced-search']/div/div[2]/input</value>
      <webElementGuid>c047791c-5c85-4c61-8dd7-1abe0e870c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1181d6b5-444a-42b1-8c8d-4e6865aef84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>dc89f6c8-66c1-41c5-8e4f-7cd9bc3975ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
