<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Submit</name>
   <tag></tag>
   <elementGuidId>0c32760d-ca8b-41f5-9db0-72b7642e5be9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='submit_contact_us']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit_contact_us</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c7d60a0-0190-4906-9868-8be3539de302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit_button</value>
      <webElementGuid>55655b70-afeb-4210-8036-f40d1878756d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit_contact_us</value>
      <webElementGuid>fc521d71-3ea2-4a2b-9fbe-d28232b0f854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>3dd60a94-f5c6-4411-96e0-fd5d6f0e121a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_contact_us&quot;)</value>
      <webElementGuid>e18801f3-f60e-4acd-ba71-6d938676ad5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='submit_contact_us']</value>
      <webElementGuid>075a64ec-26f2-4aaa-a816-56c5c6833133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pop-up-contact-us']/div/div/div/div[2]/div[10]/div</value>
      <webElementGuid>8f3fd788-6ecd-429f-8514-77bd2bb1006c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div</value>
      <webElementGuid>cc4e59ee-70df-4238-9718-fce2fbb9d3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'submit_contact_us' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>1ab4e7ce-f19d-4a31-9857-5ba3968b0e11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
