<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TABLE OF CONTENTS</name>
   <tag></tag>
   <elementGuidId>474bc232-46ec-4c4a-b7b0-477fd14ed0ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div[3]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.TOC_header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9c53f06-b1fd-4d14-ab85-eedb5daad0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TOC_header</value>
      <webElementGuid>10134b88-5b6e-4369-a19e-cbd34b2d8253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TABLE OF CONTENTS</value>
      <webElementGuid>9920e67f-5019-49cb-b528-d58ee8c16ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;BlogDetail_wrapBlogDetail__QvBFm&quot;]/div[@class=&quot;blog_detail&quot;]/div[@class=&quot;left_col&quot;]/div[@class=&quot;BlogTOC_wrapTOC__NkGlT&quot;]/div[@class=&quot;TOC_header&quot;]</value>
      <webElementGuid>652c5e25-af43-4ffd-9f81-1fc5d51d8418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div[3]/div/div/div</value>
      <webElementGuid>0cea7d1f-8e5d-4d08-86db-d5398cf1f5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div</value>
      <webElementGuid>aff110c7-ea5a-44dc-9e99-8e739f3bc71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'TABLE OF CONTENTS' or . = 'TABLE OF CONTENTS')]</value>
      <webElementGuid>017fa15c-7096-4a89-a3a6-2eee61d71001</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
