<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Key performance improvements in Kata_e75e1d</name>
   <tag></tag>
   <elementGuidId>6f4cd54c-bb37-4515-8019-9e54a6baba18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='h0']/span/span/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>04537007-6e02-4903-b305-81571e39507c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Key performance improvements in Katalon Studio 9.0.0</value>
      <webElementGuid>ee348db1-2d4a-4863-ba11-010e1a180412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;h0&quot;)/span[1]/span[1]/strong[1]</value>
      <webElementGuid>d430ec31-88e6-49b7-96e6-8447c1065d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h2[@id='h0']/span/span/strong</value>
      <webElementGuid>3bec5488-ce5e-4cd3-8405-9e1f1310639e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>fab62716-3326-4381-8f52-2e3b4ee041b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Key performance improvements in Katalon Studio 9.0.0' or . = 'Key performance improvements in Katalon Studio 9.0.0')]</value>
      <webElementGuid>500afbfc-63a4-41fa-85bc-ce88c93aec15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
