<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Automation and robots</name>
   <tag></tag>
   <elementGuidId>e066e9cd-af20-417f-a799-9fb6735a5653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cmp-advanced-search']/div/div[2]/ds-suggestions/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cmp-advanced-search-suggestion__link.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eba9f935-4571-4d23-bea4-ca7481b5a8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-advanced-search-suggestion__link active</value>
      <webElementGuid>24944197-c43e-4226-81eb-4aa8ecee1750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Automation and robots</value>
      <webElementGuid>58d48e04-dd82-4688-8048-d0151e86ce61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation and robots</value>
      <webElementGuid>151750cb-530e-4b0a-b4b5-0ab8604d443a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmp-advanced-search&quot;)/div[@class=&quot;cmp-advanced-search__form ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;cmp-advanced-search__field&quot;]/ds-suggestions[@class=&quot;cmp-advanced-search__suggestion&quot;]/ul[@class=&quot;cmp-advanced-search-suggestion&quot;]/li[@class=&quot;cmp-advanced-search-suggestion__item&quot;]/a[@class=&quot;cmp-advanced-search-suggestion__link active&quot;]</value>
      <webElementGuid>7cc06722-b834-48db-8e4f-c668c89de5a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmp-advanced-search']/div/div[2]/ds-suggestions/ul/li/a</value>
      <webElementGuid>333124f4-47d1-49cc-b191-f0e4daa5d08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ds-suggestions/ul/li/a</value>
      <webElementGuid>1a60f351-7a2b-459e-93bc-3fcdc013cd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Automation and robots' and (text() = 'Automation and robots' or . = 'Automation and robots')]</value>
      <webElementGuid>593acd7d-c9be-4d2a-9bf0-d7550d163e2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
