<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_icon-search</name>
   <tag></tag>
   <elementGuidId>f1b3392e-ffe1-42a5-bb8c-9960575db607</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cmp-advanced-search']/div/div[2]/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.icon-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fbc6d07a-0f94-48d1-9560-2264e891c333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-search</value>
      <webElementGuid>e812a3b9-aed4-46c3-948f-55e7aa9f6188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmp-advanced-search&quot;)/div[@class=&quot;cmp-advanced-search__form ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;cmp-advanced-search__field&quot;]/button[@class=&quot;cmp-advanced-search__button&quot;]/i[@class=&quot;icon-search&quot;]</value>
      <webElementGuid>7e3d4c62-f075-4f9c-8543-c48f8be1f29a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmp-advanced-search']/div/div[2]/button/i</value>
      <webElementGuid>92904dc3-fc0a-4202-9b79-21ee8bea35a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/i</value>
      <webElementGuid>f20843a5-67b6-4833-9d24-fd9c3e2a5c34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
