<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cmp-advanced-search__input ng-untouch_fd955c</name>
   <tag></tag>
   <elementGuidId>d87d5f2f-8031-4fc1-97ae-860454ad4c03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.cmp-advanced-search__input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4238cc82-4246-470b-9542-d9f1c5719819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97592c67-aed5-4bc0-a51a-7bf3b423a812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b3ef0a94-6c56-4259-a522-2f313d406651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ba418563-6990-44e9-9f12-a1ce857a8da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>searchTerm</value>
      <webElementGuid>1910b263-d10b-48fd-8f27-58d956dcc508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cmp-advanced-search__input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e28fbb0a-1d73-4960-8a70-8b7d1e4c3882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>580b7efe-2f1c-4eec-933d-ee271e902f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmp-advanced-search&quot;)/div[@class=&quot;cmp-advanced-search__form ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;cmp-advanced-search__field&quot;]/input[@class=&quot;cmp-advanced-search__input ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>722f3bf0-0296-44fc-8dc3-aecfd9b9136a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='']</value>
      <webElementGuid>35f96d04-c53c-4ef2-8e1d-a0623bc74847</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cmp-advanced-search']/div/div[2]/input</value>
      <webElementGuid>20a22b2e-285d-4af9-8ac1-758c8e880206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c9193de0-50c0-4eba-8b01-c06d7b4ea084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @title = 'search' and @placeholder = 'Search']</value>
      <webElementGuid>01cdd86f-6c34-4e91-ad5b-ba58213af8f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
