<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Deloitte and Automation Anywhere Alliance</name>
   <tag></tag>
   <elementGuidId>6595d078-d308-4438-a13d-baddd0509ee1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='article-title']/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.primary-headline</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>be86ece6-27e5-4a92-9132-74dc5b4f1c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-headline</value>
      <webElementGuid>2cdd997b-420a-467f-b6b8-130651718a41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemprop</name>
      <type>Main</type>
      <value>headline</value>
      <webElementGuid>18abd5db-39fd-4040-9e02-da440fd06e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deloitte and Automation Anywhere Alliance</value>
      <webElementGuid>50dbb895-081a-4e65-a837-d2a0c6eeb68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;article-title&quot;)/h1[@class=&quot;primary-headline&quot;]</value>
      <webElementGuid>f1133977-97ad-41e4-85bd-617c61ecefa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='article-title']/h1</value>
      <webElementGuid>b5851986-4f01-452d-add6-91123fc8274b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>4b0fd983-838d-4cf5-97c5-8cbfa5efb810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Deloitte and Automation Anywhere Alliance' or . = 'Deloitte and Automation Anywhere Alliance')]</value>
      <webElementGuid>1953d854-6f0e-42a0-b1c1-3b9334e985dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
