<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_OK</name>
   <tag></tag>
   <elementGuidId>0d30ad3d-ae53-41d0-91a1-a641599801f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookie-disclosure-banner-accept</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cookie-disclosure-banner-accept']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0245f3e4-1d06-4ab2-bbb9-2a5b59a38602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cookie-disclosure-banner-accept</value>
      <webElementGuid>d7d55877-4222-4956-b304-0babc71e904e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary with-icon</value>
      <webElementGuid>157bd5ba-1d2e-4fa8-9e4f-f848bc690d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>acceptCookieDisclosureBanner(); return false;</value>
      <webElementGuid>f811143e-37a1-48d9-bf62-d49ba1090679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK﻿</value>
      <webElementGuid>48cecc97-e9a4-4d60-bf2c-98dac70cde22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookie-disclosure-banner-accept&quot;)</value>
      <webElementGuid>ddf7e898-26b9-44ed-8b05-9a7a73a2fb90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cookie-disclosure-banner-accept']</value>
      <webElementGuid>7dfc5208-cdf3-4b2a-aff7-23ace696b028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookie-disclosure-banner']/div[2]/div[2]/a</value>
      <webElementGuid>4e3d9cdd-c949-4422-b3c8-f95d7f8b5b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[191]</value>
      <webElementGuid>144ce088-1d81-4a57-adbf-b4961114253b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div[2]/a</value>
      <webElementGuid>382a3e4a-0a4f-4e0a-8e57-5226f6327c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cookie-disclosure-banner-accept' and (text() = 'OK﻿' or . = 'OK﻿')]</value>
      <webElementGuid>993d4552-81c6-4e4f-bfcf-47a15ed6ab92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
