<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK</name>
   <tag></tag>
   <elementGuidId>4a9ec1d2-c8e4-4138-8ee8-7276c2e7b2b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cookie-disclosure-banner-accept > span.btn__text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cookie-disclosure-banner-accept']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>792ec1e5-876c-4eb9-acea-60932b420fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn__text</value>
      <webElementGuid>b1175001-13a4-4670-b55a-49078f477500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>3c6d8945-ad3a-492a-830c-4b4a80600a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookie-disclosure-banner-accept&quot;)/span[@class=&quot;btn__text&quot;]</value>
      <webElementGuid>5a329099-b515-4309-bd09-b0fd61147e2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cookie-disclosure-banner-accept']/span</value>
      <webElementGuid>86c30a93-ee11-4b8a-8608-fbe831f8011e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a/span</value>
      <webElementGuid>a1caca9d-733b-48ad-8421-b43479b0c85e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>8164b3c7-86a5-4196-a383-a3e62ab66c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
