<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Learn more</name>
   <tag></tag>
   <elementGuidId>dd0a4ff5-1274-4e34-aace-ed32121e28a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon_header']/section/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.banner_link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13025a5b-38db-4021-a6cb-485e1ba69f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>banner_link</value>
      <webElementGuid>e3d5e9c9-8646-46f5-9581-67b34a2b272f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/resources-center/blog/katalon-studio-9.0.0</value>
      <webElementGuid>e0ec0837-7cc1-4d47-b61f-60fbf03381fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Learn more</value>
      <webElementGuid>897a48f8-e59d-4236-871e-540cfe59d687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon_header&quot;)/section[@class=&quot;homepage_banner&quot;]/div[@class=&quot;wrap_container&quot;]/div[@class=&quot;left_content&quot;]/a[@class=&quot;banner_link&quot;]</value>
      <webElementGuid>9a5bf1a9-e37e-4d93-b59a-743b508cb242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon_header']/section/div/div/a</value>
      <webElementGuid>0d2f40ef-7743-4ac4-b1fa-a9fa80840faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Learn more')]</value>
      <webElementGuid>b735e037-aa9d-49b3-bdd1-ce7623d23924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/resources-center/blog/katalon-studio-9.0.0')]</value>
      <webElementGuid>383a208d-30da-4eda-be8b-2f648a6bd621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7fc35447-e21a-4843-967e-d69d75ef190f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/resources-center/blog/katalon-studio-9.0.0' and (text() = 'Learn more' or . = 'Learn more')]</value>
      <webElementGuid>47f0eefe-e0b8-48da-b2ef-69d4581dab9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
