<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Why Katalon</name>
   <tag></tag>
   <elementGuidId>2ef81867-2ac2-47ff-9a69-fa25d3077eb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon_header']/section[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.top_nav_title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db0c3024-3c48-42d1-a0bc-ff67432db95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top_nav_title</value>
      <webElementGuid>0f4f7ba5-6c8c-4da3-8394-149160dbf04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-hoverable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5ba914d-bcf4-423f-8aa0-9647cd6c9a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-last-action-id</name>
      <type>Main</type>
      <value>8b6506a3-1526-413a-b1da-846060a4a1e6</value>
      <webElementGuid>bf897520-66ef-42ae-aa29-fef57378df87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Why Katalon</value>
      <webElementGuid>272b3385-533a-4ba3-b1a6-51b7d137a57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon_header&quot;)/section[@class=&quot;rebrand_header undefined&quot;]/div[@class=&quot;wrap_container&quot;]/div[@class=&quot;left_logo_and_topnav&quot;]/div[@class=&quot;katalon_topnav&quot;]/div[@class=&quot;top_nav_item have_child_menu&quot;]/div[@class=&quot;top_nav_title&quot;]</value>
      <webElementGuid>b3fce808-a819-442d-91c3-706e349fc8a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon_header']/section[2]/div/div/div/div/div</value>
      <webElementGuid>2d45959d-d949-446b-930d-de1ba60bff75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div/div</value>
      <webElementGuid>0950f080-d2a6-40a7-9d61-331621e4d69f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Why Katalon' or . = 'Why Katalon')]</value>
      <webElementGuid>68719cee-de59-4292-a5b9-5dcb1f74c855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
