<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign in</name>
   <tag></tag>
   <elementGuidId>96cbe7ab-8f01-40cb-a242-a9b5e8cffef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kc-content-wrapper']/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.button_sign_in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fdbdfebf-8eaa-444f-b8f6-337ce72120ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_sign_in</value>
      <webElementGuid>5d63b589-7c04-476e-80b3-02c070d7085b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>a0044e66-bc67-49c9-8986-e63bb41176fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-content-wrapper&quot;)/div[@class=&quot;wrapSignIn&quot;]/div[@class=&quot;list_menu_temp_for_special_page&quot;]/a[1]/div[@class=&quot;button_sign_in&quot;]</value>
      <webElementGuid>ceeadb53-7e0b-42aa-8ee2-ee59f439613d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[2]/a/div</value>
      <webElementGuid>e57479e2-3079-4046-b11d-5705a779222a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>9ed78fd1-51ca-4d1f-897c-a629b15c77b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>8da2799d-a66f-4546-924d-3065f6e1ee38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
