<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divbtn-sign-up</name>
   <tag></tag>
   <elementGuidId>bd9f7d42-447c-4b13-b9fe-0c637eb885df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='btn-sign-up']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-sign-up</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>487640ec-0f22-4dc3-843d-84bcaf0fc078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-in-btn btn-start-testing</value>
      <webElementGuid>32b7b01c-b38a-4e21-b02e-0acf273b7740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-sign-up</value>
      <webElementGuid>82714c8f-4047-4c4e-a294-45d355f37da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-sign-up&quot;)</value>
      <webElementGuid>9eb75c76-9d29-41db-9cb2-3b7e7fa835c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='btn-sign-up']</value>
      <webElementGuid>c92800bc-3d3e-46f8-b318-e5af4f44c3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-form-buttons']/div</value>
      <webElementGuid>d91c7e9d-a6b2-49c2-85c1-b71eb12b036d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div</value>
      <webElementGuid>c15a4b1f-4e34-4002-bc1b-94c1ce1e17ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'btn-sign-up']</value>
      <webElementGuid>19c94750-8de5-4447-a3af-14f65d6c1fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[7]/div</value>
      <webElementGuid>2b32819d-76eb-4938-bb13-107021ddb2d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
