<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_c-qxl3oea4lrjq</name>
   <tag></tag>
   <elementGuidId>c316982b-65c0-483d-a7ef-cedffd2cc233</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;c-qxl3oea4lrjq&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='c-qxl3oea4lrjq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5347bcdd-9eea-4cf9-a8fd-c0118cb75853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>recaptcha challenge expires in two minutes</value>
      <webElementGuid>5242ccdf-ef03-418c-bc49-af46f1811a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>c-qxl3oea4lrjq</value>
      <webElementGuid>e537c2a2-cc15-48e6-8028-c0cf78fc7ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>748ea40f-ea75-4105-ab4b-6d469ff58c44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>2225ef58-81ca-49d2-b9c5-57aa78945e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>421dacbd-e30e-4de3-b99b-42bb21071a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=vm_YDiq1BiI3a8zfbIPZjtF2&amp;k=6LcWA7gnAAAAANPXEzE9M_j1s48wcVgi54CR0ts5</value>
      <webElementGuid>2cb27939-c62a-45a4-8a04-f43c38e043bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[8]/div[4]/iframe[1]</value>
      <webElementGuid>fb95d2b2-808c-41af-9496-852040f37422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='c-qxl3oea4lrjq']</value>
      <webElementGuid>1d59f5c6-eceb-4537-aa4e-7882c98f9afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/iframe</value>
      <webElementGuid>f1ff655c-162b-4153-9982-470d698bd082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'recaptcha challenge expires in two minutes' and @name = 'c-qxl3oea4lrjq' and @src = 'https://www.google.com/recaptcha/api2/bframe?hl=en&amp;v=vm_YDiq1BiI3a8zfbIPZjtF2&amp;k=6LcWA7gnAAAAANPXEzE9M_j1s48wcVgi54CR0ts5']</value>
      <webElementGuid>a24d37d1-bcd1-4271-bbf1-2d932eb0882e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
