<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_a-qxl3oea4lrjq</name>
   <tag></tag>
   <elementGuidId>aae3eb9b-2e2e-441e-9df9-57dc2f7b899e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-qxl3oea4lrjq&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-qxl3oea4lrjq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>248477a5-ebdb-47b4-8ca3-11af1d355511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>125c144b-d54d-4a00-8b40-1dce48ec20a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>6c9c5b8f-8895-4c1a-9d4a-675aeedbec3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>db8d3da8-847d-44ca-807c-988f83066017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>ec032ae3-995d-4f6d-817f-e51e171d905d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-qxl3oea4lrjq</value>
      <webElementGuid>e484c93c-d99b-48f6-a40a-61dadb51bafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5e0588ed-1f13-4c61-a6a5-9ad5828d0bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>16878340-e2e3-4497-bebe-d2670e210fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox</value>
      <webElementGuid>3539d778-a353-4643-b56f-3804c8f4b0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcWA7gnAAAAANPXEzE9M_j1s48wcVgi54CR0ts5&amp;co=aHR0cHM6Ly9sb2dpbi5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;v=vm_YDiq1BiI3a8zfbIPZjtF2&amp;size=normal&amp;cb=fgq788pchav3</value>
      <webElementGuid>f27e7e7f-8f90-4cfa-86c5-0dd39d5db15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-content-wrapper&quot;)/div[@class=&quot;wrapSignIn&quot;]/div[@class=&quot;sign_up_section&quot;]/div[@class=&quot;sign_up_form&quot;]/form[@class=&quot;form_sign_up&quot;]/div[@class=&quot;input-div-form&quot;]/div[1]/div[@class=&quot;g-recaptcha&quot;]/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>9e6569ff-4645-4b2a-8cfb-6abeeebb6803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-qxl3oea4lrjq']</value>
      <webElementGuid>c0d395e7-5f4b-4015-a187-311f148347c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[3]/div/form/div[5]/div/div/div/div/iframe</value>
      <webElementGuid>aae6a6bd-ab97-46ae-ad2b-c5d690902dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c7650659-f37f-4a6c-be8d-7dd97ad559f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-qxl3oea4lrjq' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LcWA7gnAAAAANPXEzE9M_j1s48wcVgi54CR0ts5&amp;co=aHR0cHM6Ly9sb2dpbi5rYXRhbG9uLmNvbTo0NDM.&amp;hl=en&amp;v=vm_YDiq1BiI3a8zfbIPZjtF2&amp;size=normal&amp;cb=fgq788pchav3']</value>
      <webElementGuid>6f323bfb-2575-4cbb-8726-90311ceb8c93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
