<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>ab2b3630-5f4e-4b2f-b254-8744c34e70a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d0e5260f-fa90-4f22-ad75-3c1b3ac2a6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>92352f39-11d0-4e25-8c8f-12c690d453dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA59JcyYTVccqhohwycrITBG6sOaq1t5a3he3T-Aj_w9qNn-aIEbZplhHNmny_Z5F4TaVaz74PD7tMMonj1tbu66ROUSPeQLQtJA5Gmc8blVaHfyauszvmNr-Mvoozoz4lwLFZKZzoWhA1DaKtzlazbwnk86jvofkPfHe-H9mvvsf0RBdK84fhuuInTxqKol7AY4QRh2&amp;k=6LcWA7gnAAAAANPXEzE9M_j1s48wcVgi54CR0ts5&amp;id=2</value>
      <webElementGuid>58596378-0e71-40dc-b446-30ef04f5bbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>02fa1370-5a32-4375-8543-4bde5c137932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Katalon/Page_Sign up  Katalon Software Quality Mana_03d398/iframe_c-qxl3oea4lrjq</value>
      <webElementGuid>414eb3b1-13ee-4136-84e0-55e26042eda5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      <webElementGuid>6df11c0c-86cc-408b-ac43-8ca60cf106df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA59JcyYTVccqhohwycrITBG6sOaq1t5a3he3T-Aj_w9qNn-aIEbZplhHNmny_Z5F4TaVaz74PD7tMMonj1tbu66ROUSPeQLQtJA5Gmc8blVaHfyauszvmNr-Mvoozoz4lwLFZKZzoWhA1DaKtzlazbwnk86jvofkPfHe-H9mvvsf0RBdK84fhuuInTxqKol7AY4QRh2&amp;k=6LcWA7gnAAAAANPXEzE9M_j1s48wcVgi54CR0ts5&amp;id=2')])[6]</value>
      <webElementGuid>7667194c-1994-49fd-b67e-2e112c9965dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
      <webElementGuid>66bc72b0-83fa-4ef5-961f-42efd710c24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA59JcyYTVccqhohwycrITBG6sOaq1t5a3he3T-Aj_w9qNn-aIEbZplhHNmny_Z5F4TaVaz74PD7tMMonj1tbu66ROUSPeQLQtJA5Gmc8blVaHfyauszvmNr-Mvoozoz4lwLFZKZzoWhA1DaKtzlazbwnk86jvofkPfHe-H9mvvsf0RBdK84fhuuInTxqKol7AY4QRh2&amp;k=6LcWA7gnAAAAANPXEzE9M_j1s48wcVgi54CR0ts5&amp;id=2']</value>
      <webElementGuid>2fc3b0b6-f14e-4587-a1a0-6aa984e1dbe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
