<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputregisterFullname</name>
   <tag></tag>
   <elementGuidId>5b283058-d538-48ae-bf17-a0d21164e690</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerFullname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registerFullname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb55bf51-ef8f-45ae-869e-d5b32ad040f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerFullname</value>
      <webElementGuid>447564da-2bf3-47f3-bd06-2f7c6b7ad280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43c17b02-f1ca-4a20-b3c6-6e9e35e3be88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9f81ad8-a876-4b6f-ad9e-552fd3f70421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Full name</value>
      <webElementGuid>fe75934c-13ed-4b3a-8a3f-eb85bffa3c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>this.value = this.value.replace(/[^a-zA-Z ]/g,'')</value>
      <webElementGuid>7f9144ed-c56b-4c70-8ae7-4d984ef137cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerFullname&quot;)</value>
      <webElementGuid>8b6da2b2-6a18-4d6e-96cd-36eb1da0bcf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registerFullname']</value>
      <webElementGuid>62895653-037b-4106-9541-9ff4b53c6572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-content-wrapper']/div/div[3]/div/form/div/input</value>
      <webElementGuid>8f4bf33b-c6aa-4771-a0d1-eb3a6adf6e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>dba428b8-b864-41cb-929e-3f588fbb286c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registerFullname' and @type = 'text' and @placeholder = 'Full name']</value>
      <webElementGuid>9e2e18fe-6e46-4e9d-96c3-09b328ad2a88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
