<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enroll</name>
   <tag></tag>
   <elementGuidId>3250d374-b651-4cda-9e23-8770cc9706ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.tutor-btn-enroll.tutor-btn.tutor-course-purchase-btn.btn-enroll-view-course</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93434fb5-e318-4c15-b7c7-a3b54cb3bc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1352c5e6-7f01-474c-b354-28c9dd72a3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course</value>
      <webElementGuid>db359895-163d-4779-b466-25e82afed84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3ad5c690-68aa-4e4a-9074-625790885e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modal-registration</value>
      <webElementGuid>5e369640-6f4b-4718-987c-0c44facbb467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Enroll				</value>
      <webElementGuid>33fa0b17-e09f-4b11-810f-91dcaadc80fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-items-course&quot;)/div[@class=&quot;col-md-8 col-11 mb-sm-2&quot;]/div[@class=&quot;skillate-course-cart-btn d-lg-block&quot;]/div[@class=&quot;enroll-course-top enroll-course-element enroll-course-position&quot;]/div[@class=&quot;tutor-single-add-to-cart-box cart-required-login&quot;]/form[@class=&quot;tutor-enroll-form enroll-course-form&quot;]/div[@class=&quot;tutor-course-enroll-wrap&quot;]/button[@class=&quot;tutor-btn-enroll tutor-btn tutor-course-purchase-btn btn-enroll-view-course&quot;]</value>
      <webElementGuid>9260b2de-7bcb-435c-a686-285b0608a523</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>57e98b84-ec0a-4153-972a-4addb9f3f93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-items-course']/div[5]/div/div/div/form/div/button</value>
      <webElementGuid>35bdcd4c-7364-443b-9e03-78c7751610bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>58fea329-34b9-4d38-9236-7f9060e6e8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
										Enroll				' or . = '
										Enroll				')]</value>
      <webElementGuid>1828c389-6b29-4fd7-9c4a-14d5690bd4dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
