<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Download</name>
   <tag></tag>
   <elementGuidId>b0e33280-276d-4ec3-8869-53de77ff7fb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.download_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='studio_standalone_download_link']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a8044d0-a515-4b14-94c9-d53c93369a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>download_btn</value>
      <webElementGuid>068443bd-c641-4ba1-9151-8f1245c87261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hs-event-122140170</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1320f8a6-cef4-4950-8fde-5e003fc6fdf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download</value>
      <webElementGuid>f9b2fe25-1e29-46e1-a529-194d4f0f69b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;studio_standalone_download_link&quot;)/div[@class=&quot;download_btn&quot;]</value>
      <webElementGuid>bba49c29-a82d-4106-8620-744a43372583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='studio_standalone_download_link']/div</value>
      <webElementGuid>30399fa9-91ec-40c8-a31c-84f9af194667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div[2]/a/div</value>
      <webElementGuid>49ee92cb-cc55-4f45-995c-f82804a31993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Download' or . = 'Download')]</value>
      <webElementGuid>d7fff428-61e2-4c23-83d7-6a036abfde07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
