<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ver. 8.6.8</name>
   <tag></tag>
   <elementGuidId>277adfb4-c913-441e-99e4-d7a73693ea4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.version_option</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div[2]/div/div[2]/div/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40b2a15f-11bd-4dee-92e8-565617dfdfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>version_option</value>
      <webElementGuid>8196b8d0-cda8-4027-b142-24625f2daeee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-version</name>
      <type>Main</type>
      <value>latest_8</value>
      <webElementGuid>8f4b099d-f1ee-46c6-909a-6386984ae987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-hoverable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e7d342f3-a8d8-4b9d-94d5-f5451481c41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-last-action-id</name>
      <type>Main</type>
      <value>0f540e20-1805-459d-bb36-3c19d1499361</value>
      <webElementGuid>7b7d07c5-ce99-4250-b9a2-392d9bfcf828</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver. 8.6.8</value>
      <webElementGuid>001eb5ea-51de-4431-ba2f-77e7b000764c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;DownloadPage_wrapDownload__oXIBd&quot;]/div[@class=&quot;download_page_container&quot;]/div[@class=&quot;download_section&quot;]/div[@class=&quot;choose_os_and_version_section&quot;]/div[@class=&quot;dropdown_section&quot;]/div[@class=&quot;dropdown_version active&quot;]/div[@class=&quot;list_options_version&quot;]/div[@class=&quot;version_option&quot;]</value>
      <webElementGuid>5b00439f-76a3-4010-a3a5-af0707941c8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[2]/div/div/div[2]/div[2]/div</value>
      <webElementGuid>6b2128b1-d61d-407a-bb67-3eb4a5564527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div[2]/div[2]/div</value>
      <webElementGuid>0af572a4-1518-4aca-b2e1-fd80359e3b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ver. 8.6.8' or . = 'Ver. 8.6.8')]</value>
      <webElementGuid>592320f9-5928-4934-bb89-048ac21ed5a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
