<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search roles for experienced hires</name>
   <tag></tag>
   <elementGuidId>8c52d31e-a47b-4969-9996-cc36e061488a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='careers-search']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.search-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6c5730f5-7da7-44a0-b2f4-b505261db221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-link</value>
      <webElementGuid>2349c853-7df8-4cc0-9cb6-29157248bb04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://apply.deloitte.com/careers/SearchJobs?sort=relevancy&amp;3_5_3=479</value>
      <webElementGuid>753a6217-94e9-4a30-9c78-fd42ca1be110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Search roles for experienced hires
    </value>
      <webElementGuid>06514cf4-5bd8-4b4b-b04c-b878f6c40acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;careers-search&quot;)/a[@class=&quot;search-link&quot;]</value>
      <webElementGuid>26595509-d55f-4cc8-8e84-4336fed2e7c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='careers-search']/a</value>
      <webElementGuid>4ca830b9-536c-455e-899a-3350f18aee37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Search roles for experienced hires')]</value>
      <webElementGuid>202bfdfd-4849-4141-a49d-a32d76cc5b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://apply.deloitte.com/careers/SearchJobs?sort=relevancy&amp;3_5_3=479')]</value>
      <webElementGuid>7be67435-c0de-47d0-8cc8-4136c2c26830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/a</value>
      <webElementGuid>0fd32475-03b8-48ba-8417-0b3b6c24a852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://apply.deloitte.com/careers/SearchJobs?sort=relevancy&amp;3_5_3=479' and (text() = '
        Search roles for experienced hires
    ' or . = '
        Search roles for experienced hires
    ')]</value>
      <webElementGuid>281b20ba-4d76-4954-95d4-b8f22df746a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
