<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Operate with dynamic control</name>
   <tag></tag>
   <elementGuidId>a02c450f-62ba-4b45-8ad6-79cbceb64553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fluidBrandedHeadertfotHeader']/div/div/div[2]/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.brand-color-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>43abec61-3523-4cf8-9458-1bc52eab7c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand-color-white</value>
      <webElementGuid>71c05a5e-af7a-4082-b3d5-4f49b867610b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Operate with dynamic control</value>
      <webElementGuid>d8345a07-9274-43c2-92ff-ead42df9d9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fluidBrandedHeadertfotHeader&quot;)/div[@class=&quot;fluid-branded-container fluid-branded-header-cont aos-init aos-animate&quot;]/div[@class=&quot;fluid-branded-row&quot;]/div[@class=&quot;fluid-branded-col-sm-6 fluid-branded-col-sm-pull-6&quot;]/div[@class=&quot;fluid-branded-header-text brand-color-white&quot;]/h1[@class=&quot;brand-color-white&quot;]</value>
      <webElementGuid>c47ab224-8985-4b0c-97d8-01adfdd28fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fluidBrandedHeadertfotHeader']/div/div/div[2]/div/h1</value>
      <webElementGuid>839324a0-0fee-43d9-b673-3422b38e9b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>d98abc13-5e70-4909-8f2c-88d0102231d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Operate with dynamic control' or . = 'Operate with dynamic control')]</value>
      <webElementGuid>5e739437-ff8e-4d34-b657-1d67624c8152</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
